version: '3.6'

services:

  web:
    image: parsemaker/docker-magento:1.9.3.9
    container_name: web
    volumes:
      - .:/root/
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - env

  db:
    image: mysql:8.0
    container_name: db
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - env

volumes:
  db-data:
